FROM centos:8.3.2011

RUN yum install -y --nogpgcheck epel-release && \
    yum install -y --nogpgcheck https://repo.saltstack.com/py3/redhat/salt-py3-repo-latest.el8.noarch.rpm && \
    yum update -y && \
    yum install -y virt-what salt-minion nano tree net-tools git && \
    yum clean all && \
    rm -rf /var/cache/yum

RUN sed -i "s|#master: salt|master: salt-master|g" /etc/salt/minion

ENTRYPOINT ["salt-minion", "-l", "debug"]